### ISSUE TITLE
[ORACLE] Cannot cast type bytea to json

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#325] opened 2022-09-16 06:08 UTC
**Error on Import schema**
import of schema in "migration_test" database started
Target YugabyteDB version: 11.2-YB-2.14.2.0-b0
schemas to be present in target database: [public]
dropping schema 'public' in target database
creating schema 'public' in target database...
importing       TYPE      done
importing   SEQUENCE      done
importing      TABLE      
    ERROR: cannot cast type bytea to json (SQLSTATE 42846)
    STATEMENT: ALTER TABLE products ADD CONSTRAINT products_json_c CHECK ( (CASE WHEN product_details::json IS NULL THEN true ELSE true END));
ERROR: cannot cast type bytea to json (SQLSTATE 42846)

**Schema**
**Table Creation**
PROMPT Creating tables 

create table customers (
  customer_id     integer generated by default on null as identity,
  email_address   varchar2(255 char) not null,
  full_name       varchar2(255 char) not null)
;

create table stores (
  store_id          integer generated by default on null as identity ,
  store_name        varchar2(255 char) not null,
  web_address       varchar2(100 char),
  physical_address  varchar2(512 char),
  latitude          number,
  longitude         number,
  logo              blob,
  logo_mime_type    varchar2(512 char),
  logo_filename     varchar2(512 char),
  logo_charset      varchar2(512 char),
  logo_last_updated date)
;

create table products (
  product_id         integer generated by default on null as identity ,
  product_name       varchar2(255 char) not null,
  unit_price         number(10,2),
  product_details    blob,
  product_image      blob,
  image_mime_type    varchar2(512 char),
  image_filename     varchar2(512 char),
  image_charset      varchar2(512 char),
  image_last_updated date)
;

create table orders (
  order_id        integer
                  generated by default on null as identity,
  order_datetime  timestamp not null,
  customer_id     integer not null,
  order_status    varchar2(10 char) not null,
  store_id        integer not null)
;

create table shipments (
  shipment_id          integer
                       generated by default on null as identity,
  store_id             integer not null,
  customer_id          integer not null,
  delivery_address     varchar2(512 char) not null,
  shipment_status      varchar2(100 char) not null)
;

create table order_items (
  order_id        integer not null,
  line_item_id    integer not null,
  product_id      integer not null,
  unit_price      number(10,2) not null,
  quantity        integer not null,
  shipment_id     integer)
;

create table inventory (
  inventory_id          integer
                        generated by default on null as identity,
  store_id              integer not null,
  product_id            integer not null,
  product_inventory     integer not null)
;

PROMPT Creating indexes

create index customers_name_i on customers ( full_name );
create index orders_customer_id_i on orders ( customer_id );
create index orders_store_id_i on orders ( store_id );
create index shipments_store_id_i on shipments ( store_id );
create index shipments_customer_id_i on shipments ( customer_id );
create index order_items_shipment_id_i on order_items ( shipment_id );
create index inventory_product_id_i on inventory ( product_id );

**Constraint Creation**
PROMPT Add constraints to tables

alter table customers add constraint customers_pk primary key (customer_id);

alter table customers add constraint customers_email_u unique (email_address);

alter table stores add constraint stores_pk primary key (store_id);

alter table stores add constraint store_name_u unique (store_name);

alter table stores add constraint store_at_least_one_address_c
  check (
    web_address is not null or physical_address is not null
  );

alter table products add constraint products_pk primary key (product_id);

**_**alter table products add constraint products_json_c
                     check ( product_details is json );**_**

alter table orders add constraint orders_pk primary key (order_id);

alter table orders add constraint orders_customer_id_fk
   foreign key (customer_id) references customers (customer_id);

alter table orders add constraint  orders_status_c
                  check ( order_status in
                    ( 'CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED'));

alter table orders add constraint orders_store_id_fk foreign key (store_id)
   references stores (store_id);

alter table shipments add constraint shipments_pk primary key (shipment_id);

alter table shipments add constraint shipments_store_id_fk
   foreign key (store_id) references stores (store_id);

alter table shipments add constraint shipments_customer_id_fk
   foreign key (customer_id) references customers (customer_id);

alter table shipments add constraint shipment_status_c
                  check ( shipment_status in
                    ( 'CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'));

alter table order_items add constraint order_items_pk primary key ( order_id, line_item_id );

alter table order_items add constraint order_items_order_id_fk
   foreign key (order_id) references orders (order_id);

alter table order_items add constraint order_items_shipment_id_fk
   foreign key (shipment_id) references shipments (shipment_id);

alter table order_items add constraint order_items_product_id_fk
   foreign key (product_id) references products (product_id);

alter table order_items add constraint order_items_product_u unique ( product_id, order_id );

alter table inventory add constraint inventory_pk primary key (inventory_id);

alter table inventory add constraint inventory_store_product_u unique (store_id, product_id);

alter table inventory add constraint inventory_store_id_fk
   foreign key (store_id) references stores (store_id);

alter table inventory add constraint inventory_product_id_fk
   foreign key (product_id) references products (product_id);

**Yb-Voyager logs**
2022-09-16 06:04:46 INFO logging.go:66 Args: [./yb-voyager import schema --export-dir /home/ubuntu/export-dir --target-db-host 10.9.200.131 --target-db-user ybvoyager --target-db-password password --target-db-name migration_test --target-db-user ybvoyager --start-clean --yes]
2022-09-16 06:04:46 INFO importSchemaYugabyteDB.go:131 Extracting the metainfo about the source database.
2022-09-16 06:04:46 INFO logging.go:33 import of schema in "migration_test" database started
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading TYPE in dir /home/ubuntu/export-dir/schema/types/type.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading SEQUENCE in dir /home/ubuntu/export-dir/schema/sequences/sequence.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading TABLE in dir /home/ubuntu/export-dir/schema/tables/table.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading INDEX in dir /home/ubuntu/export-dir/schema/tables/INDEXES_table.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading PACKAGE in dir /home/ubuntu/export-dir/schema/packages/package.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading VIEW in dir /home/ubuntu/export-dir/schema/views/view.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading TRIGGER in dir /home/ubuntu/export-dir/schema/triggers/trigger.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading FUNCTION in dir /home/ubuntu/export-dir/schema/functions/function.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading PROCEDURE in dir /home/ubuntu/export-dir/schema/procedures/procedure.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading PARTITION in dir /home/ubuntu/export-dir/schema/partitions/partition.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading MVIEW in dir /home/ubuntu/export-dir/schema/mviews/mview.sql
2022-09-16 06:04:47 INFO analyzeSchema.go:539 Reading SYNONYM in dir /home/ubuntu/export-dir/schema/synonyms/synonym.sql
2022-09-16 06:04:47 INFO logging.go:33 schemas to be present in target database: [public]

2022-09-16 06:04:47 INFO importSchema.go:133 check if schema "public" exists: fetchedSchema: "public", err: %!s(<nil>)
2022-09-16 06:04:47 INFO logging.go:33 dropping schema 'public' in target database
2022-09-16 06:04:51 INFO importSchema.go:133 check if schema "public" exists: fetchedSchema: "", err: no rows in result set
2022-09-16 06:04:51 INFO logging.go:33 creating schema 'public' in target database...
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:67 Importing "/home/ubuntu/export-dir/schema/types/type.sql"
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:79 Running query "SET SCHEMA 'public'" on the target DB
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:85 Running query "SET client_encoding TO 'UTF8'" on the target DB
2022-09-16 06:04:51 INFO analyzeSchema.go:539 Reading TYPE in dir /home/ubuntu/export-dir/schema/types/type.sql
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:67 Importing "/home/ubuntu/export-dir/schema/sequences/sequence.sql"
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:79 Running query "SET SCHEMA 'public'" on the target DB
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:85 Running query "SET client_encoding TO 'UTF8'" on the target DB
2022-09-16 06:04:51 INFO analyzeSchema.go:539 Reading SEQUENCE in dir /home/ubuntu/export-dir/schema/sequences/sequence.sql
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:67 Importing "/home/ubuntu/export-dir/schema/tables/table.sql"
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:79 Running query "SET SCHEMA 'public'" on the target DB
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:85 Running query "SET client_encoding TO 'UTF8'" on the target DB
2022-09-16 06:04:51 INFO analyzeSchema.go:539 Reading TABLE in dir /home/ubuntu/export-dir/schema/tables/table.sql
2022-09-16 06:04:51 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
CREATE TABLE customers (
	customer_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 393 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	email_address varchar(255) NOT NULL,
	full_name varchar(255) NOT NULL,
	PRIMARY KEY (customer_id)
) ;
2022-09-16 06:04:56 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
ALTER TABLE customers ADD UNIQUE (email_address);
2022-09-16 06:05:00 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
CREATE TABLE inventory (
	inventory_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 567 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	store_id numeric(38) NOT NULL,
	product_id numeric(38) NOT NULL,
	product_inventory numeric(38) NOT NULL,
	PRIMARY KEY (inventory_id)
) ;
2022-09-16 06:05:04 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
ALTER TABLE inventory ADD UNIQUE (store_id,product_id);
2022-09-16 06:05:09 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
CREATE TABLE orders (
	order_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1951 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	order_datetime timestamp NOT NULL,
	customer_id numeric(38) NOT NULL,
	order_status varchar(10) NOT NULL,
	store_id numeric(38) NOT NULL,
	PRIMARY KEY (order_id)
) ;
2022-09-16 06:05:13 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
ALTER TABLE orders ADD CONSTRAINT orders_status_c CHECK ( order_status in ( 'CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED'));
2022-09-16 06:05:13 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
CREATE TABLE order_items (
	order_id numeric(38) NOT NULL,
	line_item_id numeric(38) NOT NULL,
	product_id numeric(38) NOT NULL,
	unit_price double precision NOT NULL,
	quantity numeric(38) NOT NULL,
	shipment_id numeric(38),
	PRIMARY KEY (order_id,line_item_id)
) ;
2022-09-16 06:05:17 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
ALTER TABLE order_items ADD UNIQUE (product_id,order_id);
2022-09-16 06:05:22 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
CREATE TABLE products (
	product_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 47 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	product_name varchar(255) NOT NULL,
	unit_price double precision,
	product_details bytea,
	product_image bytea,
	image_mime_type varchar(512),
	image_filename varchar(512),
	image_charset varchar(512),
	image_last_updated timestamp,
	PRIMARY KEY (product_id)
) ;
2022-09-16 06:05:26 INFO importSchemaYugabyteDB.go:96 Execute STATEMENT:
ALTER TABLE products ADD CONSTRAINT products_json_c CHECK ( (CASE WHEN product_details::json IS NULL THEN true ELSE true END));
2022-09-16 06:05:26 ERROR importSchemaYugabyteDB.go:99 Previous SQL statement failed with error: ERROR: cannot cast type bytea to json (SQLSTATE 42846)

**Comment by kneeraj** [comment] 2022-09-26 06:58
Hi @sanyamsinghal , are you planning to close this as duplicate of #342.

**Comment by sanyamsinghal** [comment] 2022-09-26 08:02
Hi @kneeraj looks like I have mentioned this issue by mistake in #342 
My Apologies for the confusion. Unlinking them.

**Closed** 2022-11-28 12:50 UTC

**Comment by shubham-yb** [comment] 2022-11-28 12:52
Has BLOB/CLOB issue at its root.
