### ISSUE TITLE
Couldn't parse the TOC file to collect the tablenames for data files

### ISSUE THREAD

**Issue by jcpkanuri** [yugabyte/yb-voyager#382] opened 2022-09-30 21:28 UTC
when running export data from source (Postgres DB) ,  Couldn't parse the TOC file to collect the tablenames for data files: exit status 1
 INFO logging.go:33 Data export started.
2022-09-30 14:55:46 INFO pg_dump_export_data.go:90 toc.dat file successfully created.
2022-09-30 14:55:47 ERROR logging.go:28 Couldn't parse the TOC file to collect the tablenames for data files: exit status 1

**Comment by sanyamsinghal** [comment] 2022-10-03 07:22
hi @jcpkanuri can you please share the output of this command: `pg_restore -l data` after changing going to the export-dir
That will help us to debug the issue.

**Comment by jcpkanuri** [comment] 2022-10-03 18:16
Hi @sanyamsinghal ,
The pg_restore -l data is taking forever to give the response.Not sure if it is stuck. 

Could you please let me know if we have any other way to check what is happening?

**Comment by jcpkanuri** [comment] 2022-10-04 19:51
@sanyamsinghal 
Here is the content from the log file:
2022-10-03 08:37:57 INFO postgres.go:42 Table "test_dbo.t_test_table" has 4 rows.

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading SCHEMA in dir /home/export-dir/schema/schemas/schema.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading TYPE in dir /home/export-dir/schema/types/type.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading DOMAIN in dir /home/export-dir/schema/domains/domain.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading SEQUENCE in dir /home/export-dir/schema/sequences/sequence.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading TABLE in dir /home/export-dir/schema/tables/table.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading INDEX in dir /home/export-dir/schema/tables/INDEXES_table.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading RULE in dir /home/export-dir/schema/rules/rule.sql

2022-10-03 08:37:57 INFO analyzeSchema.go:527 Reading FUNCTION in dir /home/export-dir/schema/functions/function.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading AGGREGATE in dir /home/export-dir/schema/aggregates/aggregate.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading PROCEDURE in dir /home/export-dir/schema/procedures/procedure.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading VIEW in dir /home/export-dir/schema/views/view.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading TRIGGER in dir /home/export-dir/schema/triggers/trigger.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading MVIEW in dir /home/export-dir/schema/mviews/mview.sql

2022-10-03 08:37:58 INFO analyzeSchema.go:527 Reading EXTENSION in dir /home/export-dir/schema/extensions/extension.sql

2022-10-03 08:37:58 INFO pg_dump_export_data.go:49 Running command: pg_dump   -- I have delete because of security reasons

2022-10-03 08:37:58 INFO logging.go:33 Data export started.

2022-10-03 08:38:10 INFO pg_dump_export_data.go:90 toc.dat file successfully created.

2022-10-03 08:38:14 ERROR logging.go:28 Couldn't parse the TOC file to collect the tablenames for data files: exit status 1

**Comment by sanyamsinghal** [comment] 2022-10-06 18:29
hi, @jcpkanuri can you please try again the same migration with the latest beta release? It will add more info to logs and the console in case of failures, which will help us to debug better.

**Comment by ShivanshGahlot** [comment] 2022-10-11 10:56
Duplicate of https://github.com/yugabyte/yb-voyager/issues/423

**Closed by ShivanshGahlot** 2022-10-11 10:56 UTC
