### ISSUE TITLE
[ORACLE] export-data for schema with partitions failing

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#589] opened 2022-11-15 12:03 UTC
Description : The export-data action hangs when performed on a schema involving tables with partitions.

**Schema used**
```
DROP TABLE ORDER_ITEMS_RANGE_PARTITIONED;
create table ORDER_ITEMS_RANGE_PARTITIONED (
  order_id        integer
                  generated by default on null as identity,
  order_datetime  timestamp not null,
  customer_id     integer not null,
  order_status    varchar2(10 char) not null,
  store_id        integer not null)
PARTITION BY RANGE (order_id,customer_id)
(PARTITION p1 VALUES LESS THAN (50,8),
PARTITION p2 VALUES LESS THAN (70,15),
PARTITION p3 VALUES LESS THAN (80,15))
ENABLE ROW MOVEMENT;
```

**Data used**
```
Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (1,to_timestamp('04-FEB-2018 13.20.22.245676861','DD-MON-YYYY HH24.MI.SS.FF'),3,1,'CANCELLED');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (2,to_timestamp('08-FEB-2018 20.58.10.472721115','DD-MON-YYYY HH24.MI.SS.FF'),45,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (3,to_timestamp('09-FEB-2018 23.17.07.242517323','DD-MON-YYYY HH24.MI.SS.FF'),18,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (4,to_timestamp('10-FEB-2018 13.43.36.061928731','DD-MON-YYYY HH24.MI.SS.FF'),45,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (5,to_timestamp('11-FEB-2018 18.01.30.906119035','DD-MON-YYYY HH24.MI.SS.FF'),2,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (6,to_timestamp('13-FEB-2018 20.11.48.702319539','DD-MON-YYYY HH24.MI.SS.FF'),74,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (7,to_timestamp('22-FEB-2018 00.57.11.011114421','DD-MON-YYYY HH24.MI.SS.FF'),9,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (8,to_timestamp('22-FEB-2018 15.00.52.003836100','DD-MON-YYYY HH24.MI.SS.FF'),109,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (9,to_timestamp('23-FEB-2018 13.25.26.824165229','DD-MON-YYYY HH24.MI.SS.FF'),127,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (10,to_timestamp('23-FEB-2018 14.02.10.185866897','DD-MON-YYYY HH24.MI.SS.FF'),106,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (11,to_timestamp('24-FEB-2018 02.05.31.903891365','DD-MON-YYYY HH24.MI.SS.FF'),68,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (12,to_timestamp('24-FEB-2018 09.54.16.110488621','DD-MON-YYYY HH24.MI.SS.FF'),127,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (13,to_timestamp('24-FEB-2018 11.44.43.690930433','DD-MON-YYYY HH24.MI.SS.FF'),99,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (14,to_timestamp('24-FEB-2018 17.50.02.729015363','DD-MON-YYYY HH24.MI.SS.FF'),101,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (15,to_timestamp('26-FEB-2018 17.43.17.366895115','DD-MON-YYYY HH24.MI.SS.FF'),119,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (16,to_timestamp('26-FEB-2018 23.42.54.082180815','DD-MON-YYYY HH24.MI.SS.FF'),119,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (17,to_timestamp('27-FEB-2018 07.47.46.606030496','DD-MON-YYYY HH24.MI.SS.FF'),16,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (18,to_timestamp('28-FEB-2018 18.42.54.719578735','DD-MON-YYYY HH24.MI.SS.FF'),39,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (19,to_timestamp('01-MAR-2018 06.09.26.634522376','DD-MON-YYYY HH24.MI.SS.FF'),49,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (20,to_timestamp('01-MAR-2018 10.07.32.467335385','DD-MON-YYYY HH24.MI.SS.FF'),3,3,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (21,to_timestamp('01-MAR-2018 18.38.27.438668681','DD-MON-YYYY HH24.MI.SS.FF'),144,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (22,to_timestamp('01-MAR-2018 22.55.29.698737465','DD-MON-YYYY HH24.MI.SS.FF'),80,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (23,to_timestamp('02-MAR-2018 11.52.28.359515482','DD-MON-YYYY HH24.MI.SS.FF'),67,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (24,to_timestamp('02-MAR-2018 15.53.19.496456408','DD-MON-YYYY HH24.MI.SS.FF'),81,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (25,to_timestamp('03-MAR-2018 06.39.48.533448772','DD-MON-YYYY HH24.MI.SS.FF'),42,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (26,to_timestamp('03-MAR-2018 09.30.59.972993409','DD-MON-YYYY HH24.MI.SS.FF'),126,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (27,to_timestamp('03-MAR-2018 16.28.34.339865950','DD-MON-YYYY HH24.MI.SS.FF'),148,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (28,to_timestamp('05-MAR-2018 00.33.33.690222408','DD-MON-YYYY HH24.MI.SS.FF'),139,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (29,to_timestamp('06-MAR-2018 11.03.10.204845586','DD-MON-YYYY HH24.MI.SS.FF'),55,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (30,to_timestamp('06-MAR-2018 17.53.59.405863523','DD-MON-YYYY HH24.MI.SS.FF'),206,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (31,to_timestamp('07-MAR-2018 10.12.11.248485798','DD-MON-YYYY HH24.MI.SS.FF'),122,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (32,to_timestamp('07-MAR-2018 19.55.05.581612443','DD-MON-YYYY HH24.MI.SS.FF'),32,3,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (33,to_timestamp('08-MAR-2018 01.20.10.569196457','DD-MON-YYYY HH24.MI.SS.FF'),65,1,'COMPLETE');
```

Actual : Export-data action fails.
Expected : Export-data must pass.

**Comment by sanyamsinghal** [comment] 2022-11-15 12:28
hi @chetank-yb it went through for me with `main` and `0.81` branches. I tested with a schema having this table and one more table with LIST PARITTIONING
This is the output:
```
[centos@ip-10-9-2-160 oracle-test_partition-migration]$ yb-voyager export data --export-dir ${EXPORT_DIR}         --source-db-type ${SOURCE_DB_TYPE}         --source-db-host ${SOURCE_DB_HOST}         --source-db-user ${SOURCE_DB_USER}         --source-db-password ${SOURCE_DB_PASSWORD}        --source-db-name ${SOURCE_DB_NAME} --source-db-schema ${SOURCE_DB_SCHEMA} --start-clean
Note: Using current working directory as export directory
Using DB Name for export.
export of data for source type as 'oracle'
Num tables to export: 10
table list for data export: [ACCOUNTS_LIST_PARTITIONED CSV_FILE_TEST DEPARTMENTS EMPLOYEES JOBS JOB_HISTORY LOCATIONS ORDER_ITEMS_RANGE_PARTITIONED REGIONS VIEW_TABLE1]
Table "ACCOUNTS_LIST_PARTITIONED" has 6 partitions: [P_NORTHCENTRAL P_NORTHEAST P_NORTHWEST P_SOUTHCENTRAL P_SOUTHEAST P_SOUTHWEST]
Table "ORDER_ITEMS_RANGE_PARTITIONED" has 3 partitions: [P1 P2 P3]
calculating approx num of rows to export for each table...
Initiating data export.
Data export started.
Exported tables:- {CSV_FILE_TEST,  DEPARTMENTS,  EMPLOYEES,  JOBS,  JOB_HISTORY,  LOCATIONS,  ORDER_ITEMS_RANGE_PARTITIONED,  ORDER_ITEMS_RANGE_PARTITIONED PARTITION(P1),  ORDER_ITEMS_RANGE_PARTITIONED PARTITION(P2),  ORDER_ITEMS_RANGE_PARTITIONED PARTITION(P3),  REGIONS,  VIEW_TABLE1,  ACCOUNTS_LIST_PARTITIONED PARTITION(P_SOUTHWEST),  ACCOUNTS_LIST_PARTITIONED PARTITION(P_NORTHWEST),  ACCOUNTS_LIST_PARTITIONED PARTITION(P_NORTHEAST),  ACCOUNTS_LIST_PARTITIONED PARTITION(P_SOUTHEAST),  ACCOUNTS_LIST_PARTITIONED PARTITION(P_SOUTHCENTRAL),  ACCOUNTS_LIST_PARTITIONED,  ACCOUNTS_LIST_PARTITIONED PARTITION(P_NORTHCENTRAL)}

TABLE                                   	ROW COUNT
ACCOUNTS_LIST_PARTITIONED               	0
ACCOUNTS_LIST_PARTITIONED_P_NORTHCENTRAL	154385
ACCOUNTS_LIST_PARTITIONED_P_NORTHEAST   	230885
ACCOUNTS_LIST_PARTITIONED_P_NORTHWEST   	114874
ACCOUNTS_LIST_PARTITIONED_P_SOUTHCENTRAL	115493
ACCOUNTS_LIST_PARTITIONED_P_SOUTHEAST   	153778
ACCOUNTS_LIST_PARTITIONED_P_SOUTHWEST   	230585
CSV_FILE_TEST                           	0
DEPARTMENTS                             	0
EMPLOYEES                               	0
JOBS                                    	0
JOB_HISTORY                             	0
LOCATIONS                               	23
ORDER_ITEMS_RANGE_PARTITIONED           	0
ORDER_ITEMS_RANGE_PARTITIONED_P1        	33
ORDER_ITEMS_RANGE_PARTITIONED_P2        	0
ORDER_ITEMS_RANGE_PARTITIONED_P3        	0
REGIONS                                 	4
VIEW_TABLE1                             	0

Export of data complete ✅
```

**Comment by sanyamsinghal** [comment] 2022-11-15 18:26
Closing this issue since it is not reproducible.

**Closed by sanyamsinghal** 2022-11-15 18:26 UTC
Labels: bug, triage
