### ISSUE TITLE
[ORACLE] All synonyms created as part of BI schema are not migrated

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#680] opened 2022-12-15 14:25 UTC
**Git hub repo to download latest schema** : https://github.com/oracle/db-sample-schemas/releases/latest
**Schema to be tested** : BI

The BI schema has only synonyms and not tables. However while export schema all the synonym create statements can be found in failed.sql

The contents of failed.sql can be found below, 

```
ubuntu@ip-10-9-15-224:~/export-dir-bi/schema$ cat failed.sql 
CREATE OR REPLACE VIEW bi.channels AS SELECT * FROM sh.channels;

CREATE OR REPLACE VIEW bi.costs AS SELECT * FROM sh.costs;

CREATE OR REPLACE VIEW bi.countries AS SELECT * FROM sh.countries;

CREATE OR REPLACE VIEW bi.customers AS SELECT * FROM sh.customers;

CREATE OR REPLACE VIEW bi.products AS SELECT * FROM sh.products;

CREATE OR REPLACE VIEW bi.promotions AS SELECT * FROM sh.promotions;

CREATE OR REPLACE VIEW bi.sales AS SELECT * FROM sh.sales;

CREATE OR REPLACE VIEW bi.times AS SELECT * FROM sh.times;
```

@sanyamsinghal, could you please have a look at this issue.

**Comment by priyanshi-yb** [comment] 2022-12-16 07:28
Duplicate of #673

**Closed by priyanshi-yb** 2022-12-16 07:28 UTC
Labels: triage
