### ISSUE TITLE
Bug: Non transactional writes using yb_disable_transactional_writes throwing errors

### ISSUE THREAD

**Issue by sanyamsinghal** [yugabyte/yb-voyager#239] opened 2022-08-18 11:51 UTC
As mentioned in https://github.com/yugabyte/yugabyte-db/issues/12464 (reproducible following the steps mentioned). Server throws: `ERROR:  Illegal state: Used read time is not set`
This has been observed with the `2.15` yb version also, making the non-transactional behavior for COPY impossible.

**Comment by amit-yb** [comment] 2022-08-19 09:05
[read_time_is_not_set__schema.tar.gz](https://github.com/yugabyte/yb-voyager/files/9380722/read_time_is_not_set__schema.tar.gz)

**Comment by amit-yb** [comment] 2022-08-19 09:06
```
dvdrental=# select version();
                                                                                         version

----------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------
 PostgreSQL 11.2-YB-2.15.0.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 12.0.1 (https://github.com/yug
abyte/llvm-project.git bdb147e675d8c87cee72cc1f87c4b82855977d94), 64-bit
(1 row)

dvdrental=# SET yb_disable_transactional_writes TO true;
SET

dvdrental=# truncate film cascade;
NOTICE:  truncate cascades to table "film_actor"
NOTICE:  truncate cascades to table "film_category"
NOTICE:  truncate cascades to table "inventory"
NOTICE:  truncate cascades to table "rental"
NOTICE:  truncate cascades to table "payment"
TRUNCATE TABLE

dvdrental=# COPY public.film (film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext) FROM stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.

>> 133	Chamber Italian	A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria	2006	1	7	4.99	117	14.99	NC-17	2013-05-26 14:50:58.951	{Trailers}	'chamber':1 'fate':4 'husband':11 'italian':2 'monkey':16 'moos':8 'must':13 'nigeria':18 'overcom':14 'reflect':5

>> 384	Grosse Wonderful	A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia	2006	1	5	4.99	49	19.99	R	2013-05-26 14:50:58.951	{"Behind the Scenes"}	'australia':18 'cat':8 'drama':5 'epic':4 'explor':11 'gross':1 'moos':16 'must':13 'redeem':14 'wonder':2

>> \.
WARNING:  Batched COPY is not supported on table with non RI trigger. Defaulting to using one transaction for the entire copy.
HINT:  Set rows_per_transaction option to `0` to disable batching and remove this warning.
ERROR:  Illegal state: Used read time is not set

dvdrental=# select count(*) from film;
 count
-------
     1
(1 row)

dvdrental=# select film_id from film;
 film_id
---------
     133
(1 row)
```
Schema of the offending table public.film:
```
CREATE TABLE public.film (
    film_id integer DEFAULT nextval('public.film_film_id_seq'::regclass) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    release_year public.year,
    language_id smallint NOT NULL,
    rental_duration smallint DEFAULT 3 NOT NULL,
    rental_rate numeric(4,2) DEFAULT 4.99 NOT NULL,
    length smallint,
    replacement_cost numeric(5,2) DEFAULT 19.99 NOT NULL,
    rating public.mpaa_rating DEFAULT 'G'::public.mpaa_rating,
    last_update timestamp without time zone DEFAULT now() NOT NULL,
    special_features text[],
    fulltext tsvector NOT NULL
);
```

**Comment by sushantrmishra** [comment] 2022-08-24 05:54
This issues is fixed by commit https://github.com/yugabyte/yugabyte-db/commit/b9b764d1f526e10d3b4af2fc6a59db3560370b6c .

**Comment by ymahajan** [comment] 2022-08-31 16:06
@kneeraj - Can this be closed now?

**Comment by amit-yb** [comment] 2022-09-01 06:41
The issue is not seen anymore in the 2.15.2 and 2.14 branches.

**Closed by amit-yb** 2022-09-01 06:41 UTC
Labels: bug, GA1.0, dbissue
