### ISSUE TITLE
Verify/Explore an appropriate order to import object types for the different source db types

### ISSUE THREAD

**Issue by rahulb-yb** [yugabyte/yb-voyager#380] opened 2022-09-30 10:04 UTC
The order in which yb-voyager imports object types does not consider the possibility of dependencies (for eg. table definition being dependent on function definitions in PG). We need to explore a good order to import the various object types so as to avoid DDLs cascading in failure due to dependencies, as much as possible

**Comment by amit-yb** [comment] 2022-10-07 06:18
Duplicate of https://github.com/yugabyte/yb-voyager/issues/410

**Closed by amit-yb** 2022-10-07 06:18 UTC
Labels: enhancement, GA1.0
