### ISSUE TITLE
[ORACLE] Incorrect number of rows imported into yb cluster when data import is interrupted multiple times

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#310] opened 2022-09-07 12:00 UTC
**Steps to recreate**
1. Start the import data and interrupt multiple times (I did it thrice).
2. Once the import data is done, check the row count in yb cluster.

Expected : Row counts must be same (exported and imported number of rows).
Actual : The row count does not match.

**SCHEMA**

DROP TABLE SEQUENCE_TESTER;

CREATE TABLE SEQUENCE_TESTER(
    id NUMBER PRIMARY KEY,
    title VARCHAR2(255)
);

DROP SEQUENCE id_seq;
CREATE SEQUENCE id_seq
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000000000
    CYCLE
    CACHE 2;

DECLARE 
    title VARCHAR2(255);
BEGIN
 FOR A IN 1..1000000 LOOP
    title := dbms_random.string('A', 20);
    INSERT INTO SEQUENCE_TESTER VALUES(id_seq.NEXTVAL, title);
 END LOOP;
END;
/

COMMIT;

********************************************************************************************************************************
**Imported number of rows in yugabyte cluster**

![Image](https://user-images.githubusercontent.com/100332069/188873579-1cb0e0b6-87d6-4e30-af17-6251346f081e.png)

********************************************************************************************************************************
**Import data status**

![Image](https://user-images.githubusercontent.com/100332069/188873972-1f0b84ee-7a02-4b92-bfea-1c96847d2009.png)

**Comment by sanyamsinghal** [comment] 2022-09-07 13:04
@chetank-yb please share the following details:
1. Exact command used for `import data`
2. The log file for this experiment
3. Is it consistently reproducible? Steps?
4. Which branch of repo were you using

**Comment by sanyamsinghal** [comment] 2022-09-07 13:44
Thanks @chetank-yb 
Which target YBDB version you used?

**Comment by sanyamsinghal** [comment] 2022-09-09 10:06
@chetank-yb Closing this since repro is not happening. 
Please feel free to reopen the ticket if you are able to repro the issue.

**Closed by sanyamsinghal** 2022-09-09 10:06 UTC
Labels: bug, triage
