### ISSUE TITLE
voyager fails to connect to source db if password contains `@`

### ISSUE THREAD

**Issue by jcpkanuri** [yugabyte/yb-voyager#383] opened 2022-09-30 21:35 UTC
You can try in your environment as follows:

Set password using @ special char in it and run yb-voyager source schema migration, you will see the error message in yb-voyager.log file

For example you should this message in your log:

INFO pg_dump_extract_schema.go:27 Running command: pg_dump "postgresql://xxxxxx:Xxxxx@12@yugabyte.com:5432/reqstore?sslmode=prefer" --schema-only --no-owner -f /home/export-dir/temp/sample.sql

INFO pg_dump_extract_schema.go:33 pg_dump: error: could not translate host name [12@yugabyte.com](mailto:12@yugabyte.com) to address: Name or service not known

**Comment by amit-yb** [comment] 2022-10-03 05:12
Tracking clear-text password issue in a separate ticket: https://github.com/yugabyte/yb-voyager/issues/386
This issue seems to be about handling special characters in the username/password. @priyanshi-yb This looks like a duplicate of the issue that you fixed recently. Please link the associated ticket and git-commit in a comment and close this ticket.

**Comment by priyanshi-yb** [comment] 2022-10-03 05:26
Fixing this issue of passwords in this PR https://github.com/yugabyte/yb-voyager/pull/369.

**Closed by priyanshi-yb** 2022-10-03 05:26 UTC

**Comment by amit-yb** [comment] 2022-10-03 05:34
Duplicate of https://github.com/yugabyte/yb-voyager/issues/361
